name: Push docker image

on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        required: true
        type: string
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN:
        required: true

env:
  CONTAINER_REGISTERY: registry.digitalocean.com/tmsolution-cr

jobs:

  compute_tag:
    name: Compute tag.
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      TAG: ${{ steps.build-tag.outputs.tag-output }}      
    steps:
      - id: build-tag
        run: echo "tag-output=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_OUTPUT

  push_image:
    name: Push image to CR.
    runs-on: ubuntu-latest
    needs: compute_tag
    steps:
      - name: Download docker image artifact.
        uses: actions/download-artifact@v3
        with:
          name: identityapi
      - name: Load Docker image
        run: docker load --input ${{inputs.IMAGE_NAME}}.tar
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with: 
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Display secrets
        run: echo ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Login to CR
        run: doctl registry login --expiry-seconds 600
      - name: Push image to DigitalOcean CR
        run: docker push ${{env.CONTAINER_REGISTERY}}/${{inputs.IMAGE_NAME}}:${{needs.compute_tag.outputs.TAG}}