name: Build and push .NET application.

on:
  workflow_call:
    inputs:
      SOLUTION_FILE:
        required: true
        type: string
      PROJECT_FILE:
        required: true
        type: string
      TEST_PROJECT_FILE:
        required: true
        type: string
        

  
jobs:
        
  build:
    name: Build .NET application.
    runs-on: ubuntu-latest
#     needs: compute_tag
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore ${{ inputs.SOLUTION_FILE }}
      - name: Build
        run: dotnet build ${{ inputs.PROJECT_FILE }} --no-restore
      - name: Test
        run: dotnet test ${{ inputs.TEST_PROJECT_FILE }} --verbosity normal
      - name: Publish
        run: dotnet publish ${{ inputs.PROJECT_FILE }} -c Release
      
