name: Build and push .NET application.

on:
  workflow_call:
    inputs:
      SOLUTION_FILE:
        required: true
        type: string
      PROJECT_FILE:
        required: true
        type: string
      TEST_PROJECT_FILE:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string
      DOCKER_FILE:
        required: true
        type: string
      PUSH_IMAGE:
        type: boolean
        default: false
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN:
        required: true
        

  
jobs:

#   compute_tag:
#     name: Compute tag.
#     runs-on: ubuntu-latest
#     if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
#     # Map a step output to a job output
#     outputs:
#       TAG: ${{ steps.build-tag.outputs.tag-output }}      
#     steps:
#       - id: build-tag
#         run: echo "tag-output=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_OUTPUT
        
  build:
    name: Build .NET application.
    runs-on: ubuntu-latest
#     needs: compute_tag
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore ${{ inputs.SOLUTION_FILE }}
      - name: Build
        run: dotnet build ${{ inputs.PROJECT_FILE }} --no-restore
      - name: Test
        run: dotnet test ${{ inputs.TEST_PROJECT_FILE }} --verbosity normal
      - name: Publish
        run: dotnet publish ${{ inputs.PROJECT_FILE }} -c Release
  
  push:
    if: inputs.PUSH_IMAGE == true
    uses: itsbibeksaini/github-workflows/.github/workflows/docker-build-and-push.yml@main
    needs: build
    with:
      IMAGE_NAME: ${{ inputs.IMAGE_NAME }}
      DOCKER_FILE: ${{ inputs.DOCKER_FILE }} 
      PUSH_IMAGE: ${{ inputs.PUSH_IMAGE }}
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      