name: Build and push .NET application.

on:
  workflow_call:
    inputs:
      SOLUTION_FILE:
        required: true
        type: string
      PROJECT_FILE:
        required: true
        type: string
      TEST_PROJECT_FILE:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string
      DOCKER_FILE:
        required: true
        type: string
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN:
        required: true
        
env:
  REGISTRY_NAME: "registry.digitalocean.com/tmsolution-cr"  

  
jobs:

#   compute_tag:
#     name: Compute tag.
#     runs-on: ubuntu-latest
#     if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
#     # Map a step output to a job output
#     outputs:
#       TAG: ${{ steps.build-tag.outputs.tag-output }}      
#     steps:
#       - id: build-tag
#         run: echo "tag-output=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_OUTPUT
        
  build-and-push:
    name: Build and push .NET application.
    runs-on: ubuntu-latest
#     needs: compute_tag
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore ${{ inputs.SOLUTION_FILE }}
      - name: Build
        run: dotnet build ${{ inputs.PROJECT_FILE }} --no-restore
      - name: Test
        run: dotnet test ${{ inputs.TEST_PROJECT_FILE }} --verbosity normal
      - name: Publish
        run: dotnet publish ${{ inputs.PROJECT_FILE }} -c Release
      # Build a Docker image of your application in your registry and tag the image with the $GITHUB_SHA.
      - name: Build container image
        run: docker build -f ${{inputs.DOCKER_FILE}} -t ${{ env.REGISTRY_NAME }}/${{inputs.IMAGE_NAME}}:$(echo $GITHUB_SHA | head -c7) .
      # Install doctl.
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600
      - name: Push image to DigitalOcean Container Registry
        run: docker push ${{ env.REGISTRY_NAME }}/${{inputs.IMAGE_NAME}}:$(echo $GITHUB_SHA | head -c7)
