name: Build and push .NET application.

on:
  workflow_call:
    inputs:
      SOLUTION_FILE:
        required: true
        type: string
      PROJECT_FILE:
        required: true
        type: string
      TEST_PROJECT_FILE:
        required: true
        type: string
  
jobs:

  compute_tag:
    name: Compute tag.
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
    # Map a step output to a job output
    outputs:
      TAG: ${{ steps.build-tag.outputs.tag-output }}      
    steps:
      - id: build-tag
        run: echo "tag-output=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_OUTPUT
        
  build-and-push:
    name: Build and push .NET application.
    runs-on: ubuntu-latest
    needs: compute_tag
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore ${{ inputs.SOLUTION_FILE }}
      - name: Build
        run: dotnet build ${{ inputs.PROJECT_FILE }} --no-restore
      - name: Test
        run: dotnet test ${{ inputs.TEST_PROJECT_FILE }} --verbosity normal
      - name: Publish
        run: dotnet publish ${{ inputs.PROJECT_FILE }} -c Release
